# This file is maintained by Tedium - manual edits will be overwritten!
name: CI
"on":
  - push
jobs:
  check-go:
    runs-on: ubuntu-latest
    container:
      image: docker.io/golang:1.26.4@sha256:792443b89f65105abba56b9bd5e97f680a80074ac62fc844a584212f8c8102c3
    steps:
      - uses: markormesher/ci-resources/setup@483c89c13fab98a3760dddba5898d696b207cd8f # v0.7.0
      - run: ./task deps-go
      - run: ./task lint-go
  ci-all:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - check-go
      - img-build-push
    container:
      image: docker.io/busybox:1.38.0@sha256:fd8d9aa63ba2f0982b5304e1ee8d3b90a210bc1ffb5314d980eb6962f1a9715d
    steps:
      - run: |2
          results=$(echo '${{ toJson(needs) }}' | (grep '"result"' || echo))
          if echo "$results" | grep -q "failure\|cancelled\|skipped"; then
            echo "One or more jobs failed, were cancelled, or were skipped" >&2
            exit 1
          fi
          echo "All jobs passed"
  img-build-push:
    runs-on: ubuntu-latest
    needs:
      - check-go
    permissions:
      packages: write
    steps:
      - uses: markormesher/ci-resources/setup@483c89c13fab98a3760dddba5898d696b207cd8f # v0.7.0
      - run: buildah login ghcr.io -u "${{ github.actor }}" -p "${{ github.token }}"
      - run: ./task imgrefs
      - run: ./task imgbuild
      - run: ./task imgpush
